inherit_mode:
  merge:
    - Include

Rails:
 Enabled: true

AllCops:
 TargetRubyVersion: 2.6
 Include:
   - '**/Rakefile'
   - '**/Gemfile'
   - '**/config.ru'
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']